//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBasedTrainingServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.Ratings = new HashSet<Ratings>();
            this.Tags = new HashSet<Tags>();
            this.CourseVideos = new HashSet<CourseVideo>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public string Language { get; set; }
        public string URL { get; set; }
        public string PublisherName { get; set; }
        public string PublisherEmail { get; set; }
    
        public virtual ICollection<Ratings> Ratings { get; set; }
        public virtual ICollection<Tags> Tags { get; set; }
        public virtual ICollection<CourseVideo> CourseVideos { get; set; }
    }
}
